### ISSUE TITLE
Sord fails when run on discordrb

### ISSUE THREAD

**Issue by connorshea** [AaronC81/sord#1]
sord-0.2.0/lib/sord/logging.rb:13:in `silent?': uninitialized class variable @@silent in Sord::Logging (NameError)

I ran it on a local copy of [discordrb](https://github.com/meew0/discordrb) since it has YARD documentation, it didn't like that very much :P 

```
Connors-MacBook-Pro:discordrb connorshea$ gem install sord
Fetching sord-0.2.0.gem
Fetching colorize-0.8.1.gem
Successfully installed colorize-0.8.1
Successfully installed sord-0.2.0
Parsing documentation for colorize-0.8.1
Installing ri documentation for colorize-0.8.1
Parsing documentation for sord-0.2.0
Installing ri documentation for sord-0.2.0
Done installing documentation for colorize, sord after 0 seconds
2 gems installed
Connors-MacBook-Pro:discordrb connorshea$ sord defs.rbi
Traceback (most recent call last):
        14: from /Users/connorshea/.rbenv/versions/2.6.2/bin/sord:23:in `<main>'
        13: from /Users/connorshea/.rbenv/versions/2.6.2/bin/sord:23:in `load'
        12: from /Users/connorshea/.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/sord-0.2.0/exe/sord:4:in `<top (required)>'
        11: from /Users/connorshea/.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/sord-0.2.0/lib/sord/rbi_generator.rb:125:in `run'
        10: from /Users/connorshea/.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/sord-0.2.0/lib/sord/rbi_generator.rb:125:in `each'
         9: from /Users/connorshea/.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/sord-0.2.0/lib/sord/rbi_generator.rb:130:in `block in run'
         8: from /Users/connorshea/.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/sord-0.2.0/lib/sord/rbi_generator.rb:58:in `add_methods'
         7: from /Users/connorshea/.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/sord-0.2.0/lib/sord/rbi_generator.rb:58:in `each'
         6: from /Users/connorshea/.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/sord-0.2.0/lib/sord/rbi_generator.rb:71:in `block in add_methods'
         5: from /Users/connorshea/.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/sord-0.2.0/lib/sord/rbi_generator.rb:71:in `map'
         4: from /Users/connorshea/.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/sord-0.2.0/lib/sord/rbi_generator.rb:71:in `each'
         3: from /Users/connorshea/.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/sord-0.2.0/lib/sord/rbi_generator.rb:93:in `block (2 levels) in add_methods'
         2: from /Users/connorshea/.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/sord-0.2.0/lib/sord/logging.rb:82:in `omit'
         1: from /Users/connorshea/.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/sord-0.2.0/lib/sord/logging.rb:35:in `generic'
/Users/connorshea/.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/sord-0.2.0/lib/sord/logging.rb:13:in `silent?': uninitialized class variable @@silent in Sord::Logging (NameError)
Did you mean?  silent=
               silent?
        7: from /Users/connorshea/.rbenv/versions/2.6.2/bin/sord:23:in `<main>'
        6: from /Users/connorshea/.rbenv/versions/2.6.2/bin/sord:23:in `load'
        5: from /Users/connorshea/.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/sord-0.2.0/exe/sord:4:in `<top (required)>'
        4: from /Users/connorshea/.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/sord-0.2.0/lib/sord/rbi_generator.rb:118:in `run'
        3: from /Users/connorshea/.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/sord-0.2.0/lib/sord/rbi_generator.rb:151:in `rescue in run'
        2: from /Users/connorshea/.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/sord-0.2.0/lib/sord/logging.rb:60:in `error'
        1: from /Users/connorshea/.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/sord-0.2.0/lib/sord/logging.rb:37:in `generic'
/Users/connorshea/.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/sord-0.2.0/lib/sord/logging.rb:13:in `silent?': uninitialized class variable @@silent in Sord::Logging (NameError)
```

I was at the v3.3.0 tag for the discordrb repo, if that matters at all.

Also, you might want to add a GitHub issue template :)

**Comment by AaronC81** [comment]
Good catch - tests didn't pick this up because `silent` was always being set to `false` before each test.

Update to version 0.2.1 of the gem and it should work fine.

I'll set up an issue template tomorrow!
